BEGIN TRANSACTION;
DROP TABLE IF EXISTS "dates";
CREATE TABLE IF NOT EXISTS "dates" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Nombre"	TEXT NOT NULL,
	"Valor"	INTEGER NOT NULL,
	"Fecha_Hora"	INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
